//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EShopStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EShopStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EShopStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (neslouží pro zadávání adresy a kontaktů.).
        /// </summary>
        internal static string AddressControl_notest_description {
            get {
                return ResourceManager.GetString("AddressControl_notest_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string AdministrationMode_Cart {
            get {
                return ResourceManager.GetString("AdministrationMode_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string AdministrationMode_Categories {
            get {
                return ResourceManager.GetString("AdministrationMode_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifiers.
        /// </summary>
        internal static string AdministrationMode_Classifiers {
            get {
                return ResourceManager.GetString("AdministrationMode_Classifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Shop.
        /// </summary>
        internal static string AdministrationMode_Header {
            get {
                return ResourceManager.GetString("AdministrationMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Shop Administration.
        /// </summary>
        internal static string AdministrationMode_HeaderAdministration {
            get {
                return ResourceManager.GetString("AdministrationMode_HeaderAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My orders.
        /// </summary>
        internal static string AdministrationMode_MyOrders {
            get {
                return ResourceManager.GetString("AdministrationMode_MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string AdministrationMode_Orders {
            get {
                return ResourceManager.GetString("AdministrationMode_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string AdministrationMode_Products {
            get {
                return ResourceManager.GetString("AdministrationMode_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Aliases.
        /// </summary>
        internal static string AdministrationMode_UrlAliases {
            get {
                return ResourceManager.GetString("AdministrationMode_UrlAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musíte souhlasit s obchodními podmínkami.
        /// </summary>
        internal static string AdminOrderControl_approval_error {
            get {
                return ResourceManager.GetString("AdminOrderControl_approval_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Souhlasím s &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;obchodními podmínkami&lt;/a&gt;.&lt;span&gt;.
        /// </summary>
        internal static string AdminOrderControl_approval_text {
            get {
                return ResourceManager.GetString("AdminOrderControl_approval_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body celkem :.
        /// </summary>
        internal static string AdminOrderControl_BodyCelkem {
            get {
                return ResourceManager.GetString("AdminOrderControl_BodyCelkem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dopravné :.
        /// </summary>
        internal static string AdminOrderControl_Dopravne {
            get {
                return ResourceManager.GetString("AdminOrderControl_Dopravne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturovaná suma :.
        /// </summary>
        internal static string AdminOrderControl_FakturovanaSuma {
            get {
                return ResourceManager.GetString("AdminOrderControl_FakturovanaSuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace o ceně.
        /// </summary>
        internal static string AdminOrderControl_InformaceOCene {
            get {
                return ResourceManager.GetString("AdminOrderControl_InformaceOCene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalogová cena celkem :.
        /// </summary>
        internal static string AdminOrderControl_KatalogovaCeneCelkem {
            get {
                return ResourceManager.GetString("AdminOrderControl_KatalogovaCeneCelkem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro konečné odeslání objednávky.
        /// </summary>
        internal static string AdminOrderControl_order_text {
            get {
                return ResourceManager.GetString("AdminOrderControl_order_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit údaje pro příští objednávku..
        /// </summary>
        internal static string AdminOrderControl_save_delivery_addres_as_main {
            get {
                return ResourceManager.GetString("AdminOrderControl_save_delivery_addres_as_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložte objednávku pro sdružení, nebo případnou úpravu.
        /// </summary>
        internal static string AdminOrderControl_save_text {
            get {
                return ResourceManager.GetString("AdminOrderControl_save_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;VYPLŇTE DORUČOVACÍ ÚDAJE&lt;/b&gt;.
        /// </summary>
        internal static string AdminOrderControl_warning {
            get {
                return ResourceManager.GetString("AdminOrderControl_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalogová cena přidružené objednávky musí být vyšší než {0}Kč.
        /// </summary>
        internal static string AdminOrdersControl_AsociatePriceLimitMessage {
            get {
                return ResourceManager.GetString("AdminOrdersControl_AsociatePriceLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate selected orders.
        /// </summary>
        internal static string AdminOrdersControl_AsociateSelectedOrders {
            get {
                return ResourceManager.GetString("AdminOrdersControl_AsociateSelectedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated.
        /// </summary>
        internal static string AdminOrdersControl_ColumnAssociated {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisor.
        /// </summary>
        internal static string AdminOrdersControl_ColumnOrderOwnerName {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnOrderOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active orders.
        /// </summary>
        internal static string AdminOrdersControl_Title_ActiveOrders {
            get {
                return ResourceManager.GetString("AdminOrdersControl_Title_ActiveOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order archiv.
        /// </summary>
        internal static string AdminOrdersControl_Title_OrderArchiv {
            get {
                return ResourceManager.GetString("AdminOrdersControl_Title_OrderArchiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš jedinečný odkaz.
        /// </summary>
        internal static string AdvisorCookieLinkControl_label {
            get {
                return ResourceManager.GetString("AdvisorCookieLinkControl_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to můj košik (po přepočtu).
        /// </summary>
        internal static string Anonymous_MujKosikPoPrepoctu {
            get {
                return ResourceManager.GetString("Anonymous_MujKosikPoPrepoctu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to můj košik (před přepočtem).
        /// </summary>
        internal static string Anonymous_MujKosikPredPrepoctem {
            get {
                return ResourceManager.GetString("Anonymous_MujKosikPredPrepoctem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nákupní košík.
        /// </summary>
        internal static string Anonymous_NakupniKosik {
            get {
                return ResourceManager.GetString("Anonymous_NakupniKosik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Děkujeme, Vaše objednávka proběhla úspěšně!.
        /// </summary>
        internal static string Anonymous_OrderFinish_Dekujeme {
            get {
                return ResourceManager.GetString("Anonymous_OrderFinish_Dekujeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operátorka Distribuční centrum Červený Kostelec.
        /// </summary>
        internal static string Anonymous_OrderFinish_OperatorkaCentrum {
            get {
                return ResourceManager.GetString("Anonymous_OrderFinish_OperatorkaCentrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaši objednávku si můžete prohlédnout.
        /// </summary>
        internal static string Anonymous_OrderFinish_VasiObjednavkuSiMuzeteProhlednout {
            get {
                return ResourceManager.GetString("Anonymous_OrderFinish_VasiObjednavkuSiMuzeteProhlednout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V nejbližších dnech Vás kontaktuje náš obchodní specialista, poradce Eurona, který Vám v případě Vašeho zájmu může poskytnout důležité informace, vysvětlí jak používat naše jedinečné výrobky, a pomůže Vám nastartovat kariéru pro Vaší finanční nezávislost..
        /// </summary>
        internal static string Anonymous_OrderFinish_VNejblizsichDnechVasKontaktujeme {
            get {
                return ResourceManager.GetString("Anonymous_OrderFinish_VNejblizsichDnechVasKontaktujeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V případě dalších dotazů se můžete obrátit přímo na naše operátorky:.
        /// </summary>
        internal static string Anonymous_OrderFinish_VPripadeDalsichDotazu {
            get {
                return ResourceManager.GetString("Anonymous_OrderFinish_VPripadeDalsichDotazu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zde.
        /// </summary>
        internal static string Anonymous_OrderFinish_Zde {
            get {
                return ResourceManager.GetString("Anonymous_OrderFinish_Zde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat v objednávce.
        /// </summary>
        internal static string Anonymous_PokracovatVObjednavce {
            get {
                return ResourceManager.GetString("Anonymous_PokracovatVObjednavce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to potvrzení objednávky.
        /// </summary>
        internal static string Anonymous_PotvrzeniObjednavky {
            get {
                return ResourceManager.GetString("Anonymous_PotvrzeniObjednavky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat další výrobky.
        /// </summary>
        internal static string Anonymous_PridatDalsiVyrobky {
            get {
                return ResourceManager.GetString("Anonymous_PridatDalsiVyrobky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankovní účet :.
        /// </summary>
        internal static string Anonymous_Register_BankovniUcet {
            get {
                return ResourceManager.GetString("Anonymous_Register_BankovniUcet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum narození :.
        /// </summary>
        internal static string Anonymous_Register_DatumNarozeni {
            get {
                return ResourceManager.GetString("Anonymous_Register_DatumNarozeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIČ :.
        /// </summary>
        internal static string Anonymous_Register_DIC {
            get {
                return ResourceManager.GetString("Anonymous_Register_DIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodací adresa:.
        /// </summary>
        internal static string Anonymous_Register_DodaciAdresa {
            get {
                return ResourceManager.GetString("Anonymous_Register_DodaciAdresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturační adresa:.
        /// </summary>
        internal static string Anonymous_Register_FakturacniAdresa {
            get {
                return ResourceManager.GetString("Anonymous_Register_FakturacniAdresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo pro hosta :.
        /// </summary>
        internal static string Anonymous_Register_HesloProHosta {
            get {
                return ResourceManager.GetString("Anonymous_Register_HesloProHosta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANO mám vstupní heslo pro hosta od poradce EURONA.
        /// </summary>
        internal static string Anonymous_Register_HesloProHosta_AnoText {
            get {
                return ResourceManager.GetString("Anonymous_Register_HesloProHosta_AnoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud Vám Váš obchodní specialista, poradce Eurona předal heslo pro hosta, vyplňte ho zde a pokračujte v objednávce..
        /// </summary>
        internal static string Anonymous_Register_HesloProHosta_AnoText_Tooltip {
            get {
                return ResourceManager.GetString("Anonymous_Register_HesloProHosta_AnoText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE nemám vstupní heslo pro hosta od poradce EURONA.
        /// </summary>
        internal static string Anonymous_Register_HesloProHosta_NeText {
            get {
                return ResourceManager.GetString("Anonymous_Register_HesloProHosta_NeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud Vám Váš obchodní specialista, poradce Eurona předal heslo pro hosta, vyplňte ho zde a pokračujte v objednávce..
        /// </summary>
        internal static string Anonymous_Register_HesloProHosta_Tooltip {
            get {
                return ResourceManager.GetString("Anonymous_Register_HesloProHosta_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČO :.
        /// </summary>
        internal static string Anonymous_Register_ICO {
            get {
                return ResourceManager.GetString("Anonymous_Register_ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadali jste číslo v nesprávném formátu. Zadejte jej prosím ve tvaru 123456789..
        /// </summary>
        internal static string Anonymous_Register_IvalidMobile {
            get {
                return ResourceManager.GetString("Anonymous_Register_IvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiná (prosím vyplňte).
        /// </summary>
        internal static string Anonymous_Register_JinaVyplnte {
            get {
                return ResourceManager.GetString("Anonymous_Register_JinaVyplnte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno a příjmení/Nazev :.
        /// </summary>
        internal static string Anonymous_Register_JmenoAPrijmeni {
            get {
                return ResourceManager.GetString("Anonymous_Register_JmenoAPrijmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj :.
        /// </summary>
        internal static string Anonymous_Register_Kraj {
            get {
                return ResourceManager.GetString("Anonymous_Register_Kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litujeme, Vámi zadané heslo pro hosta není správné, zadejte heslo pro hosta ve tvaru 123-1122334455. Děkujeme..
        /// </summary>
        internal static string Anonymous_Register_Litujeme {
            get {
                return ResourceManager.GetString("Anonymous_Register_Litujeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město :.
        /// </summary>
        internal static string Anonymous_Register_Mesto {
            get {
                return ResourceManager.GetString("Anonymous_Register_Mesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obchodními podmínkami.
        /// </summary>
        internal static string Anonymous_Register_ObchodnimiPodminkami {
            get {
                return ResourceManager.GetString("Anonymous_Register_ObchodnimiPodminkami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plátce DPH :.
        /// </summary>
        internal static string Anonymous_Register_PlatceDPH {
            get {
                return ResourceManager.GetString("Anonymous_Register_PlatceDPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinné údaje.
        /// </summary>
        internal static string Anonymous_Register_PovinneUdaje {
            get {
                return ResourceManager.GetString("Anonymous_Register_PovinneUdaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyplňe..
        /// </summary>
        internal static string Anonymous_Register_ProsimVyplnte {
            get {
                return ResourceManager.GetString("Anonymous_Register_ProsimVyplnte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pro Vaši další objednávku.
        /// </summary>
        internal static string Anonymous_Register_ProVasiDalsiObjednavku {
            get {
                return ResourceManager.GetString("Anonymous_Register_ProVasiDalsiObjednavku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ :.
        /// </summary>
        internal static string Anonymous_Register_PSC {
            get {
                return ResourceManager.GetString("Anonymous_Register_PSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smluvními podmínkami.
        /// </summary>
        internal static string Anonymous_Register_SmluvnimiPodminkami {
            get {
                return ResourceManager.GetString("Anonymous_Register_SmluvnimiPodminkami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stejná jako fakturační.
        /// </summary>
        internal static string Anonymous_Register_StejnaJakoFakturacni {
            get {
                return ResourceManager.GetString("Anonymous_Register_StejnaJakoFakturacni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefón :.
        /// </summary>
        internal static string Anonymous_Register_Telefon {
            get {
                return ResourceManager.GetString("Anonymous_Register_Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice :.
        /// </summary>
        internal static string Anonymous_Register_Ulice {
            get {
                return ResourceManager.GetString("Anonymous_Register_Ulice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše přihlašovací údaje.
        /// </summary>
        internal static string Anonymous_Register_VasePrihlasovaciUdaje {
            get {
                return ResourceManager.GetString("Anonymous_Register_VasePrihlasovaciUdaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyplňe!.
        /// </summary>
        internal static string Anonymous_Register_VyplntePovinnouPolozku {
            get {
                return ResourceManager.GetString("Anonymous_Register_VyplntePovinnouPolozku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Zadejte heslo ve tvaru : 420-11223344 ).
        /// </summary>
        internal static string Anonymous_Register_ZadejteHesloVeTvaru {
            get {
                return ResourceManager.GetString("Anonymous_Register_ZadejteHesloVeTvaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úhrada objednávky.
        /// </summary>
        internal static string Anonymous_UhradaObjednavky {
            get {
                return ResourceManager.GetString("Anonymous_UhradaObjednavky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítejte v našem nákupním košíku! Vytvoření objednávky je velice snadné. :-)&lt;br /&gt;V následujících 5 krocích Vás rychle provedeme objednávkou a pomůžeme Vám vyplnit potřebné údaje pro úspešné doručení zboží k Vám!.
        /// </summary>
        internal static string Anonymous_Vitejte {
            get {
                return ResourceManager.GetString("Anonymous_Vitejte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výběr dopravy:.
        /// </summary>
        internal static string Anonymous_VyberDopravy {
            get {
                return ResourceManager.GetString("Anonymous_VyberDopravy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čekající nováčci Příležitost pro Vás.
        /// </summary>
        internal static string ATP_CekajiciNovacci {
            get {
                return ResourceManager.GetString("ATP_CekajiciNovacci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diskuze.
        /// </summary>
        internal static string ATP_Diskuze {
            get {
                return ResourceManager.GetString("ATP_Diskuze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do V.I.P. Angel teamu Professional.
        /// </summary>
        internal static string ATP_DoVIPATP {
            get {
                return ResourceManager.GetString("ATP_DoVIPATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulujeme Vám pro další měsíc zůstáváte členem V.I.P. Angel team Professional.
        /// </summary>
        internal static string ATP_Gratulujeme1 {
            get {
                return ResourceManager.GetString("ATP_Gratulujeme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulujeme Vám splnil jste podmínky pro vstup do V.I.P. Angel team Professional, od následujícího měsíce můžete využívat stejné.
        /// </summary>
        internal static string ATP_Gratulujeme2 {
            get {
                return ResourceManager.GetString("ATP_Gratulujeme2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Již přijatí dnešní nováčci.
        /// </summary>
        internal static string ATP_JizPrijatiDnesniNovacci {
            get {
                return ResourceManager.GetString("ATP_JizPrijatiDnesniNovacci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lektoři.
        /// </summary>
        internal static string ATP_Lektori {
            get {
                return ResourceManager.GetString("ATP_Lektori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje cesta ke hvězdám.
        /// </summary>
        internal static string ATP_MojeCestaKeHvezdam {
            get {
                return ResourceManager.GetString("ATP_MojeCestaKeHvezdam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje pozice na ceste ke hvězdám..
        /// </summary>
        internal static string ATP_MojePoziceNaCesteKeHvezdam {
            get {
                return ResourceManager.GetString("ATP_MojePoziceNaCesteKeHvezdam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet Eurona Star nutných pro udržení.
        /// </summary>
        internal static string ATP_PocetEuronaStarProUdrzeni {
            get {
                return ResourceManager.GetString("ATP_PocetEuronaStarProUdrzeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet Eurona Star nutných pro vstup.
        /// </summary>
        internal static string ATP_PocetEuronaStarProVstup {
            get {
                return ResourceManager.GetString("ATP_PocetEuronaStarProVstup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet mých Eurona star.
        /// </summary>
        internal static string ATP_PocetMychEuronaStar {
            get {
                return ResourceManager.GetString("ATP_PocetMychEuronaStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podmínky.
        /// </summary>
        internal static string ATP_Podminky {
            get {
                return ResourceManager.GetString("ATP_Podminky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přijmout nováčka.
        /// </summary>
        internal static string ATP_PrijmoutNovacka {
            get {
                return ResourceManager.GetString("ATP_PrijmoutNovacka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrační číslo.
        /// </summary>
        internal static string ATP_RegistracniCislo {
            get {
                return ResourceManager.GetString("ATP_RegistracniCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ve V.I.P. Angel teamu Professional.
        /// </summary>
        internal static string ATP_VeVIPATP {
            get {
                return ResourceManager.GetString("ATP_VeVIPATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to výhody jako V.I.P Angel team Professional..
        /// </summary>
        internal static string ATP_VyhodyJakoVIPATP {
            get {
                return ResourceManager.GetString("ATP_VyhodyJakoVIPATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět do kanceláře.
        /// </summary>
        internal static string ATP_ZpetDoKancelare {
            get {
                return ResourceManager.GetString("ATP_ZpetDoKancelare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornění! Odešlete svou objednávku do {0} hod. Obsah nákupního košíku se každý den ve {0} hod. v noci automaticky vyprázdní..
        /// </summary>
        internal static string AutomaticEmptyCartWarning {
            get {
                return ResourceManager.GetString("AutomaticEmptyCartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Backt to catalog.
        /// </summary>
        internal static string BackToCatalog {
            get {
                return ResourceManager.GetString("BackToCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Select Advisor.
        /// </summary>
        internal static string CartControl_1VybertePoradce {
            get {
                return ResourceManager.GetString("CartControl_1VybertePoradce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Create order for advisor.
        /// </summary>
        internal static string CartControl_2VytvortePoradciObjednavku {
            get {
                return ResourceManager.GetString("CartControl_2VytvortePoradciObjednavku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string CartControl_Add {
            get {
                return ResourceManager.GetString("CartControl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string CartControl_Cart {
            get {
                return ResourceManager.GetString("CartControl_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating order as another Advisor.
        /// </summary>
        internal static string CartControl_CreateOrderAsAnotherAdvisor {
            get {
                return ResourceManager.GetString("CartControl_CreateOrderAsAnotherAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order.
        /// </summary>
        internal static string CartControl_CreateOrderButton_Text {
            get {
                return ResourceManager.GetString("CartControl_CreateOrderButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order for advisor.
        /// </summary>
        internal static string CartControl_CreateOrderForUserButton_Text {
            get {
                return ResourceManager.GetString("CartControl_CreateOrderForUserButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host :.
        /// </summary>
        internal static string CartControl_Host {
            get {
                return ResourceManager.GetString("CartControl_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet položek :.
        /// </summary>
        internal static string CartControl_ItemsCount {
            get {
                return ResourceManager.GetString("CartControl_ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K pokladně.
        /// </summary>
        internal static string CartControl_KPokladne {
            get {
                return ResourceManager.GetString("CartControl_KPokladne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Order.
        /// </summary>
        internal static string CartControl_MyOrder {
            get {
                return ResourceManager.GetString("CartControl_MyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not verified user can create only 1 order!.
        /// </summary>
        internal static string CartControl_NotVeriedUserCanOnly1OrderCreate {
            get {
                return ResourceManager.GetString("CartControl_NotVeriedUserCanOnly1OrderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODESLAT OBJEDNÁVKU A ZVOLIT PLATBU.
        /// </summary>
        internal static string CartControl_OrderAndPayButton_Text {
            get {
                return ResourceManager.GetString("CartControl_OrderAndPayButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        internal static string CartControl_Price {
            get {
                return ResourceManager.GetString("CartControl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code :.
        /// </summary>
        internal static string CartControl_ProductCode {
            get {
                return ResourceManager.GetString("CartControl_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity : .
        /// </summary>
        internal static string CartControl_ProductQuantity {
            get {
                return ResourceManager.GetString("CartControl_ProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate cart.
        /// </summary>
        internal static string CartControl_RecalculateCartButton_Text {
            get {
                return ResourceManager.GetString("CartControl_RecalculateCartButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string CartControl_RegisterButton_Text {
            get {
                return ResourceManager.GetString("CartControl_RegisterButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Shop classifiers.
        /// </summary>
        internal static string ClassifiersPage_EshopGroup {
            get {
                return ResourceManager.GetString("ClassifiersPage_EshopGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (generate register document).
        /// </summary>
        internal static string GenerateRegisterDocument {
            get {
                return ResourceManager.GetString("GenerateRegisterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        internal static string GridView_ToolTip_StornoItem {
            get {
                return ResourceManager.GetString("GridView_ToolTip_StornoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Shop Administration.
        /// </summary>
        internal static string Navigation_Administration {
            get {
                return ResourceManager.GetString("Navigation_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated Order.
        /// </summary>
        internal static string Navigation_AssociatedOrder {
            get {
                return ResourceManager.GetString("Navigation_AssociatedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated Orders.
        /// </summary>
        internal static string Navigation_AssociatedOrders {
            get {
                return ResourceManager.GetString("Navigation_AssociatedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate selected orders to advisor order.
        /// </summary>
        internal static string Navigation_AssociateSelectedOrdersToAdvisor {
            get {
                return ResourceManager.GetString("Navigation_AssociateSelectedOrdersToAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Attributes.
        /// </summary>
        internal static string Navigation_Attributes {
            get {
                return ResourceManager.GetString("Navigation_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Navigation_Categories {
            get {
                return ResourceManager.GetString("Navigation_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifiers.
        /// </summary>
        internal static string Navigation_Classifiers {
            get {
                return ResourceManager.GetString("Navigation_Classifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string Navigation_Classifier_Currencies {
            get {
                return ResourceManager.GetString("Navigation_Classifier_Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Navigation_Classifier_Currency {
            get {
                return ResourceManager.GetString("Navigation_Classifier_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string Navigation_Classifier_Highlight {
            get {
                return ResourceManager.GetString("Navigation_Classifier_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights.
        /// </summary>
        internal static string Navigation_Classifier_Highlights {
            get {
                return ResourceManager.GetString("Navigation_Classifier_Highlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status.
        /// </summary>
        internal static string Navigation_Classifier_OrderStatus {
            get {
                return ResourceManager.GetString("Navigation_Classifier_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orded statuses.
        /// </summary>
        internal static string Navigation_Classifier_OrderStatuses {
            get {
                return ResourceManager.GetString("Navigation_Classifier_OrderStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Navigation_Classifier_Payment {
            get {
                return ResourceManager.GetString("Navigation_Classifier_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string Navigation_Classifier_Payments {
            get {
                return ResourceManager.GetString("Navigation_Classifier_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        internal static string Navigation_Classifier_Shipment {
            get {
                return ResourceManager.GetString("Navigation_Classifier_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipments.
        /// </summary>
        internal static string Navigation_Classifier_Shipments {
            get {
                return ResourceManager.GetString("Navigation_Classifier_Shipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string Navigation_Classifier_VAT {
            get {
                return ResourceManager.GetString("Navigation_Classifier_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATs.
        /// </summary>
        internal static string Navigation_Classifier_VATs {
            get {
                return ResourceManager.GetString("Navigation_Classifier_VATs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPD package.
        /// </summary>
        internal static string Navigation_DPDPackage {
            get {
                return ResourceManager.GetString("Navigation_DPDPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Products.
        /// </summary>
        internal static string Navigation_MenuItem_ActionProducts {
            get {
                return ResourceManager.GetString("Navigation_MenuItem_ActionProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novinky.
        /// </summary>
        internal static string Navigation_MenuItem_DarkoveSady {
            get {
                return ResourceManager.GetString("Navigation_MenuItem_DarkoveSady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Products.
        /// </summary>
        internal static string Navigation_MenuItem_NewProducts {
            get {
                return ResourceManager.GetString("Navigation_MenuItem_NewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Products.
        /// </summary>
        internal static string Navigation_MenuItem_SpecialProducts {
            get {
                return ResourceManager.GetString("Navigation_MenuItem_SpecialProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP Products.
        /// </summary>
        internal static string Navigation_MenuItem_TopProducts {
            get {
                return ResourceManager.GetString("Navigation_MenuItem_TopProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výprodej.
        /// </summary>
        internal static string Navigation_MenuItem_Vyprodej {
            get {
                return ResourceManager.GetString("Navigation_MenuItem_Vyprodej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my cart.
        /// </summary>
        internal static string Navigation_MyCart {
            get {
                return ResourceManager.GetString("Navigation_MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Navigation_Order {
            get {
                return ResourceManager.GetString("Navigation_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Navigation_Orders {
            get {
                return ResourceManager.GetString("Navigation_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orderd to associate.
        /// </summary>
        internal static string Navigation_OrdersToAssociate {
            get {
                return ResourceManager.GetString("Navigation_OrdersToAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Navigation_Product {
            get {
                return ResourceManager.GetString("Navigation_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product comments.
        /// </summary>
        internal static string Navigation_ProductComments {
            get {
                return ResourceManager.GetString("Navigation_ProductComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Navigation_Products {
            get {
                return ResourceManager.GetString("Navigation_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Alias.
        /// </summary>
        internal static string Navigation_UrlAlias {
            get {
                return ResourceManager.GetString("Navigation_UrlAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Aliases.
        /// </summary>
        internal static string Navigation_UrlAliases {
            get {
                return ResourceManager.GetString("Navigation_UrlAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated to Advisor :.
        /// </summary>
        internal static string OrderControl_AssociationAdvisor {
            get {
                return ResourceManager.GetString("OrderControl_AssociationAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association status :.
        /// </summary>
        internal static string OrderControl_AssociationStatus {
            get {
                return ResourceManager.GetString("OrderControl_AssociationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my orders.
        /// </summary>
        internal static string OrderControl_MyOrders {
            get {
                return ResourceManager.GetString("OrderControl_MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string OrderControl_Order {
            get {
                return ResourceManager.GetString("OrderControl_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order created :.
        /// </summary>
        internal static string OrderControl_OrderCreatedUser {
            get {
                return ResourceManager.GetString("OrderControl_OrderCreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order user :.
        /// </summary>
        internal static string OrderControl_OrderUser {
            get {
                return ResourceManager.GetString("OrderControl_OrderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přijímáme platby z těchto karet.
        /// </summary>
        internal static string OrderFinish_AkceptujemeKarty {
            get {
                return ResourceManager.GetString("OrderFinish_AkceptujemeKarty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Děkujeme za Vaši objednávku!.
        /// </summary>
        internal static string OrderFinish_DekujemeZaVasiObjednavku {
            get {
                return ResourceManager.GetString("OrderFinish_DekujemeZaVasiObjednavku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podle zákona o evidenci tržeb je prodávající povinen vystavit kupujícímu účtenku. Zároveň je povinen zaevidovat přijatou tržbu u správce daně online; v případě technického výpadku pak nejpozději do 48 hodin..
        /// </summary>
        internal static string OrderFinish_EET {
            get {
                return ResourceManager.GetString("OrderFinish_EET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (nelze využít pro sdružené objednávky).
        /// </summary>
        internal static string OrderFinish_NelzeVyuzitProSdruzeneObjednavky {
            get {
                return ResourceManager.GetString("OrderFinish_NelzeVyuzitProSdruzeneObjednavky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevíte si rady, kontaktujte&lt;br/&gt; naše operátorky.
        /// </summary>
        internal static string OrderFinish_NeviteSiRady {
            get {
                return ResourceManager.GetString("OrderFinish_NeviteSiRady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc s nákupem&lt;br/&gt; i objednávkou.
        /// </summary>
        internal static string OrderFinish_PomocSNakupem {
            get {
                return ResourceManager.GetString("OrderFinish_PomocSNakupem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ptejte se e-mailem!.
        /// </summary>
        internal static string OrderFinish_PtejteSeEmailem {
            get {
                return ResourceManager.GetString("OrderFinish_PtejteSeEmailem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při platbě platební kartou je celková částka za sdružené objednávky &lt;span  style=&apos;color:#eb0a5b;font-size:18px;&apos;&gt;{0}&lt;/span&gt;.
        /// </summary>
        internal static string OrderFinish_SdruzeneObjednavkyCenaCelkem_Format {
            get {
                return ResourceManager.GetString("OrderFinish_SdruzeneObjednavkyCenaCelkem_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše objednávka byla zaznamenána v systému.&lt;br/&gt;Stav Vaší objednávky si můžete zkontrolovat v sekci.
        /// </summary>
        internal static string OrderFinish_Text {
            get {
                return ResourceManager.GetString("OrderFinish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše objednávka byla přijata.
        /// </summary>
        internal static string OrderFinish_Title {
            get {
                return ResourceManager.GetString("OrderFinish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volejte!.
        /// </summary>
        internal static string OrderFinish_Volejte {
            get {
                return ResourceManager.GetString("OrderFinish_Volejte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí obsahovat čisla, malá a velká písmena.&lt;br/&gt;Minimální délka je 8 znaků!.
        /// </summary>
        internal static string PasswordPolicyMessage {
            get {
                return ResourceManager.GetString("PasswordPolicyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte si nyní způsob úhrady Vaši objednávky.
        /// </summary>
        internal static string PayOrderControl_OrderHeader {
            get {
                return ResourceManager.GetString("PayOrderControl_OrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka není uhrazená! Můžete ji uhradiť nyní..
        /// </summary>
        internal static string PayOrderControl_OrderIsNotPayed {
            get {
                return ResourceManager.GetString("PayOrderControl_OrderIsNotPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhradit objednávku.
        /// </summary>
        internal static string PayOrderControl_PayNow {
            get {
                return ResourceManager.GetString("PayOrderControl_PayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚHRADA DOBÍRKOU.
        /// </summary>
        internal static string PayOrderControl_UhradaDobirkou {
            get {
                return ResourceManager.GetString("PayOrderControl_UhradaDobirkou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAPLATIT KARTOU ONLINE.
        /// </summary>
        internal static string PayOrderControl_UhradaKartou {
            get {
                return ResourceManager.GetString("PayOrderControl_UhradaKartou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo k přerušení transakce. Nyní se můžete vrátit zpět do objednávky a zvolit jiný způsob platby..
        /// </summary>
        internal static string Pay_TransactionWasNotSuccessfully {
            get {
                return ResourceManager.GetString("Pay_TransactionWasNotSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše transakce byla úspěšne spracována..
        /// </summary>
        internal static string Pay_TransactionWasSuccessfully {
            get {
                return ResourceManager.GetString("Pay_TransactionWasSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        internal static string ProductControl_AdditionalInformation {
            get {
                return ResourceManager.GetString("ProductControl_AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        internal static string ProductControl_AditionalInfo {
            get {
                return ResourceManager.GetString("ProductControl_AditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate products.
        /// </summary>
        internal static string ProductControl_AlternateProducts {
            get {
                return ResourceManager.GetString("ProductControl_AlternateProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate products.
        /// </summary>
        internal static string ProductControl_AlternativeProducts {
            get {
                return ResourceManager.GetString("ProductControl_AlternativeProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadní etiketa výrobku.
        /// </summary>
        internal static string ProductControl_BackList {
            get {
                return ResourceManager.GetString("ProductControl_BackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code :.
        /// </summary>
        internal static string ProductControl_Code {
            get {
                return ResourceManager.GetString("ProductControl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ProductControl_Description {
            get {
                return ResourceManager.GetString("ProductControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions for use.
        /// </summary>
        internal static string ProductControl_InstructionsForUse {
            get {
                return ResourceManager.GetString("ProductControl_InstructionsForUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product found.
        /// </summary>
        internal static string ProductControl_NoProductFound {
            get {
                return ResourceManager.GetString("ProductControl_NoProductFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reviwes Found.
        /// </summary>
        internal static string ProductControl_NoReviewsFound {
            get {
                return ResourceManager.GetString("ProductControl_NoReviewsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parfumation.
        /// </summary>
        internal static string ProductControl_Parfumation {
            get {
                return ResourceManager.GetString("ProductControl_Parfumation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictograms.
        /// </summary>
        internal static string ProductControl_Pictograms {
            get {
                return ResourceManager.GetString("ProductControl_Pictograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points :.
        /// </summary>
        internal static string ProductControl_Points {
            get {
                return ResourceManager.GetString("ProductControl_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties ....
        /// </summary>
        internal static string ProductControl_PrednostiAVlastnosti {
            get {
                return ResourceManager.GetString("ProductControl_PrednostiAVlastnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Reviews.
        /// </summary>
        internal static string ProductControl_ProductReviews {
            get {
                return ResourceManager.GetString("ProductControl_ProductReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string ProductControl_Properties {
            get {
                return ResourceManager.GetString("ProductControl_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity .
        /// </summary>
        internal static string ProductControl_Quantity {
            get {
                return ResourceManager.GetString("ProductControl_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related products.
        /// </summary>
        internal static string ProductControl_RelatedProducts {
            get {
                return ResourceManager.GetString("ProductControl_RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special effects.
        /// </summary>
        internal static string ProductControl_SpecialEffects {
            get {
                return ResourceManager.GetString("ProductControl_SpecialEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request to proccess order . Order detail can zou see in page  {0}.
        /// </summary>
        internal static string UserOrderFinishPage_Email2Central_Message {
            get {
                return ResourceManager.GetString("UserOrderFinishPage_Email2Central_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order nr.: {0}.
        /// </summary>
        internal static string UserOrderFinishPage_Email2Central_Subject {
            get {
                return ResourceManager.GetString("UserOrderFinishPage_Email2Central_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Thak You for your order&lt;/b&gt;
        ///Your order is currently in progress. Statu your order can see on : {0}.
        /// </summary>
        internal static string UserOrderFinishPage_Email2User_Message {
            get {
                return ResourceManager.GetString("UserOrderFinishPage_Email2User_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order nr.: {0}.
        /// </summary>
        internal static string UserOrderFinishPage_Email2User_Subject {
            get {
                return ResourceManager.GetString("UserOrderFinishPage_Email2User_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vánoce 2014!.
        /// </summary>
        internal static string Vanoce {
            get {
                return ResourceManager.GetString("Vanoce", resourceCulture);
            }
        }
    }
}
