//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Reports", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poradce : .
        /// </summary>
        internal static string Advisor {
            get {
                return ResourceManager.GetString("Advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Aktivity report poradce.
        /// </summary>
        internal static string AktivityReportPoradce {
            get {
                return ResourceManager.GetString("AktivityReportPoradce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivity report poradce.
        /// </summary>
        internal static string AktivityReportPoradce_Title {
            get {
                return ResourceManager.GetString("AktivityReportPoradce_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktuální zbývající kredit pro čerpání.
        /// </summary>
        internal static string AktualniZbyvajiciKreditProCerpani {
            get {
                return ResourceManager.GetString("AktualniZbyvajiciKreditProCerpani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuální nárok bonusů.
        /// </summary>
        internal static string AktualnyNarokBonusu {
            get {
                return ResourceManager.GetString("AktualnyNarokBonusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez 21% poradců.
        /// </summary>
        internal static string Bez21Poradcu {
            get {
                return ResourceManager.GetString("Bez21Poradcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobní skupina bez 21% podřízených skupin.
        /// </summary>
        internal static string Bez21Skupin {
            get {
                return ResourceManager.GetString("Bez21Skupin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body do dosažení další úrovně.
        /// </summary>
        internal static string BodyDoDosazeniDalsiUrovne {
            get {
                return ResourceManager.GetString("BodyDoDosazeniDalsiUrovne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celé skupiny.
        /// </summary>
        internal static string CeleSkupiny {
            get {
                return ResourceManager.GetString("CeleSkupiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to celkem poradců v 1.linii.
        /// </summary>
        internal static string CelkemPoradcuV1Linii {
            get {
                return ResourceManager.GetString("CelkemPoradcuV1Linii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to celkem poradců ve skupině.
        /// </summary>
        internal static string CelkemPoradcuVeSkupine {
            get {
                return ResourceManager.GetString("CelkemPoradcuVeSkupine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to celkem poradců v osobní skupině.
        /// </summary>
        internal static string CelkemPoradcuVOsobniSkupine {
            get {
                return ResourceManager.GetString("CelkemPoradcuVOsobniSkupine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postup v kariéře - provizní hladiny {0}.
        /// </summary>
        internal static string Chart_PostupVKariere {
            get {
                return ResourceManager.GetString("Chart_PostupVKariere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vývoj celkové provize.
        /// </summary>
        internal static string Chart_VyvojCelkoveProvize {
            get {
                return ResourceManager.GetString("Chart_VyvojCelkoveProvize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vývoj celkových nových registrací skupiny {0}.
        /// </summary>
        internal static string Chart_VyvojNovychRegistraciSkupiny {
            get {
                return ResourceManager.GetString("Chart_VyvojNovychRegistraciSkupiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vývoj obratu skupiny {0}.
        /// </summary>
        internal static string Chart_VyvojObratuSkupiny {
            get {
                return ResourceManager.GetString("Chart_VyvojObratuSkupiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vývoj obratu osobních objednávek {0}.
        /// </summary>
        internal static string Chart_VyvojOsobnichObjednavek {
            get {
                return ResourceManager.GetString("Chart_VyvojOsobnichObjednavek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vývoj přidelených leaderských bonusů {0}.
        /// </summary>
        internal static string Chart_VyvojPridelenychLeaderskychBosusu {
            get {
                return ResourceManager.GetString("Chart_VyvojPridelenychLeaderskychBosusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vývoj skupinových bodů {0}.
        /// </summary>
        internal static string Chart_VyvojSkupinovychBodu {
            get {
                return ResourceManager.GetString("Chart_VyvojSkupinovychBodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vývoj vlastních nových registrací {0}.
        /// </summary>
        internal static string Chart_VyvojVlastnichNovychRegistraci {
            get {
                return ResourceManager.GetString("Chart_VyvojVlastnichNovychRegistraci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to další úroveň.
        /// </summary>
        internal static string DalsiUroven {
            get {
                return ResourceManager.GetString("DalsiUroven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 1.obj..
        /// </summary>
        internal static string Datum1Obj_Column {
            get {
                return ResourceManager.GetString("Datum1Obj_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum reg..
        /// </summary>
        internal static string DatumReg_Column {
            get {
                return ResourceManager.GetString("DatumReg_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum zrušení.
        /// </summary>
        internal static string DatumVymazu_Column {
            get {
                return ResourceManager.GetString("DatumVymazu_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Denní přehled objednávek.
        /// </summary>
        internal static string DenniPrehledObjednavek {
            get {
                return ResourceManager.GetString("DenniPrehledObjednavek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denní přehled objednávek.
        /// </summary>
        internal static string DenniPrehledObjednavek_Title {
            get {
                return ResourceManager.GetString("DenniPrehledObjednavek_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Dnes zaúčtovaná produkce.
        /// </summary>
        internal static string DnesZauctovanaProdukce {
            get {
                return ResourceManager.GetString("DnesZauctovanaProdukce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnes zaúčtovaná produkce.
        /// </summary>
        internal static string DnesZauctovanaProdukce_Title {
            get {
                return ResourceManager.GetString("DnesZauctovanaProdukce_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generovat.
        /// </summary>
        internal static string Generovat {
            get {
                return ResourceManager.GetString("Generovat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generovat můj měsíční report ve formátu pdf.
        /// </summary>
        internal static string GenerovatMujMesicniReportPDF {
            get {
                return ResourceManager.GetString("GenerovatMujMesicniReportPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Historie objednávek.
        /// </summary>
        internal static string HistorieObjednavek {
            get {
                return ResourceManager.GetString("HistorieObjednavek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historie objednávek.
        /// </summary>
        internal static string HistorieObjednavek_Title {
            get {
                return ResourceManager.GetString("HistorieObjednavek_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jméno.
        /// </summary>
        internal static string Jmeno {
            get {
                return ResourceManager.GetString("Jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno sp..
        /// </summary>
        internal static string JmenoSp_Column {
            get {
                return ResourceManager.GetString("JmenoSp_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string Jmeno_Column {
            get {
                return ResourceManager.GetString("Jmeno_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kód poradce.
        /// </summary>
        internal static string KodPoradce {
            get {
                return ResourceManager.GetString("KodPoradce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kredit získaný v měsíci.
        /// </summary>
        internal static string KreditZiskanyVMesici {
            get {
                return ResourceManager.GetString("KreditZiskanyVMesici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marže.
        /// </summary>
        internal static string Marze {
            get {
                return ResourceManager.GetString("Marze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marže na tento měsíc %.
        /// </summary>
        internal static string MarzeNaTentoMesic {
            get {
                return ResourceManager.GetString("MarzeNaTentoMesic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měsíc.
        /// </summary>
        internal static string Mesic_Column {
            get {
                return ResourceManager.GetString("Mesic_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobilní telefon.
        /// </summary>
        internal static string MobilniTelefon {
            get {
                return ResourceManager.GetString("MobilniTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Nezaúčtovaná produkce v reportech.
        /// </summary>
        internal static string NezauctovanaProdukcevReportech {
            get {
                return ResourceManager.GetString("NezauctovanaProdukcevReportech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezaúčtovaná produkce v reportech.
        /// </summary>
        internal static string NezauctovanaProdukcevReportech_Title {
            get {
                return ResourceManager.GetString("NezauctovanaProdukcevReportech_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Noví poradci.
        /// </summary>
        internal static string NoviPoradci {
            get {
                return ResourceManager.GetString("NoviPoradci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noví poradci.
        /// </summary>
        internal static string NoviPoradci_Title {
            get {
                return ResourceManager.GetString("NoviPoradci_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Období : .
        /// </summary>
        internal static string Obdobi {
            get {
                return ResourceManager.GetString("Obdobi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objem pro marži.
        /// </summary>
        internal static string ObjemProMarzi_Column {
            get {
                return ResourceManager.GetString("ObjemProMarzi_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osobní aktivita.
        /// </summary>
        internal static string OsobniAktivita {
            get {
                return ResourceManager.GetString("OsobniAktivita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Osobní přehled poradce.
        /// </summary>
        internal static string OsobniPrehledPoradce {
            get {
                return ResourceManager.GetString("OsobniPrehledPoradce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobní přehled poradce.
        /// </summary>
        internal static string OsobniPrehledPoradce_Title {
            get {
                return ResourceManager.GetString("OsobniPrehledPoradce_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobní skupiny.
        /// </summary>
        internal static string OsobniSkupiny {
            get {
                return ResourceManager.GetString("OsobniSkupiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to předběžný nárok na marži pro příští měsíc % .
        /// </summary>
        internal static string PredbeznyNarokNaMarziProPristiMesic {
            get {
                return ResourceManager.GetString("PredbeznyNarokNaMarziProPristiMesic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Přehled objednávek.
        /// </summary>
        internal static string PrehledObjednavek {
            get {
                return ResourceManager.GetString("PrehledObjednavek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled objednávek.
        /// </summary>
        internal static string PrehledObjednavek_Title {
            get {
                return ResourceManager.GetString("PrehledObjednavek_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Přehled produkce skupiny.
        /// </summary>
        internal static string PrehledProdukceSkupiny {
            get {
                return ResourceManager.GetString("PrehledProdukceSkupiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Přehled produkce skupiny ATP.
        /// </summary>
        internal static string PrehledProdukceSkupinyATP {
            get {
                return ResourceManager.GetString("PrehledProdukceSkupinyATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled produkce skupiny ATP.
        /// </summary>
        internal static string PrehledProdukceSkupinyATP_Title {
            get {
                return ResourceManager.GetString("PrehledProdukceSkupinyATP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled produkce skupiny.
        /// </summary>
        internal static string PrehledProdukceSkupiny_Title {
            get {
                return ResourceManager.GetString("PrehledProdukceSkupiny_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to procentuální hladina %.
        /// </summary>
        internal static string ProcentualniHladina {
            get {
                return ResourceManager.GetString("ProcentualniHladina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro dosažení 25% marže Vám zbývá objednat výrobky za BO.
        /// </summary>
        internal static string ProDosazeni25MarzeZbyvaObjednat {
            get {
                return ResourceManager.GetString("ProDosazeni25MarzeZbyvaObjednat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro dosažení 30% marže Vám zbývá objednat výrobky za BO.
        /// </summary>
        internal static string ProDosazeni30MarzeZbyvaObjednat {
            get {
                return ResourceManager.GetString("ProDosazeni30MarzeZbyvaObjednat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provize v aktuálním měsíci ze skupiny.
        /// </summary>
        internal static string ProvizeVAktualnimMesiciZeSkupiny {
            get {
                return ResourceManager.GetString("ProvizeVAktualnimMesiciZeSkupiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provize v aktuálním měsíci z vlastního objemu.
        /// </summary>
        internal static string ProvizeVAktualnimMesiciZVLObjemu {
            get {
                return ResourceManager.GetString("ProvizeVAktualnimMesiciZVLObjemu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro získání dalšího Eura zbývá objednat za.
        /// </summary>
        internal static string ProZiskaniDalsihoEuraZbyvaObjednatZa {
            get {
                return ResourceManager.GetString("ProZiskaniDalsihoEuraZbyvaObjednatZa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to První linie.
        /// </summary>
        internal static string PrvniLinie {
            get {
                return ResourceManager.GetString("PrvniLinie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok.
        /// </summary>
        internal static string Rok_Column {
            get {
                return ResourceManager.GetString("Rok_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdil.hl..
        /// </summary>
        internal static string RozdilHl_Column {
            get {
                return ResourceManager.GetString("RozdilHl_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to součet bonusů.
        /// </summary>
        internal static string SoucetBonusu {
            get {
                return ResourceManager.GetString("SoucetBonusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telefon domů.
        /// </summary>
        internal static string TelefonDomu {
            get {
                return ResourceManager.GetString("TelefonDomu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telefon do práce.
        /// </summary>
        internal static string TelefonDoPrace {
            get {
                return ResourceManager.GetString("TelefonDoPrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon sp..
        /// </summary>
        internal static string TelefonSp_Column {
            get {
                return ResourceManager.GetString("TelefonSp_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Telefon_Column {
            get {
                return ResourceManager.GetString("Telefon_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAŠE DIAMANTOVÁ CESTA.
        /// </summary>
        internal static string VaseDiamantovaCesta {
            get {
                return ResourceManager.GetString("VaseDiamantovaCesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš nevyčerpaný nárok na slevu ke konci minulého měsíce.
        /// </summary>
        internal static string VasNevycerpanyNarokNaSlevuKeKonciMinulehoMesice {
            get {
                return ResourceManager.GetString("VasNevycerpanyNarokNaSlevuKeKonciMinulehoMesice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš nevyčerpaný nárok na slevu (NRZ+) k poslední aktualizaci.
        /// </summary>
        internal static string VasNevycerpanyNarokNaSlevuNRZ {
            get {
                return ResourceManager.GetString("VasNevycerpanyNarokNaSlevuNRZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vyplacená provize v měně .
        /// </summary>
        internal static string VyplacenaProvizeVMene {
            get {
                return ResourceManager.GetString("VyplacenaProvizeVMene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět do mojí kanceláře.
        /// </summary>
        internal static string ZpetDoMojiKancelare {
            get {
                return ResourceManager.GetString("ZpetDoMojiKancelare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Zrušení poradci.
        /// </summary>
        internal static string ZruseniPoradci {
            get {
                return ResourceManager.GetString("ZruseniPoradci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušení poradci.
        /// </summary>
        internal static string ZruseniPoradci_Title {
            get {
                return ResourceManager.GetString("ZruseniPoradci_Title", resourceCulture);
            }
        }
    }
}
