//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RadGrid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadGrid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Resources.RadGrid", typeof(RadGrid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditColumnText {
            get {
                return ResourceManager.GetString("EditColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to group or reorder.
        /// </summary>
        internal static string RadGrid_ClientSettings_ClientMessages_DragToGroupOrReorder {
            get {
                return ResourceManager.GetString("RadGrid_ClientSettings_ClientMessages_DragToGroupOrReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to resize.
        /// </summary>
        internal static string RadGrid_ClientSettings_ClientMessages_DragToResize {
            get {
                return ResourceManager.GetString("RadGrid_ClientSettings_ClientMessages_DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop here to reorder.
        /// </summary>
        internal static string RadGrid_ClientSettings_ClientMessages_DropHereToReorder {
            get {
                return ResourceManager.GetString("RadGrid_ClientSettings_ClientMessages_DropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string RadGrid_ClientSettings_ClientMessages_PagerTooltipFormatString {
            get {
                return ResourceManager.GetString("RadGrid_ClientSettings_ClientMessages_PagerTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string RadGrid_FilterMenu_ToolTip {
            get {
                return ResourceManager.GetString("RadGrid_FilterMenu_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse group.
        /// </summary>
        internal static string RadGrid_GroupingSettings_CollapseTooltip {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand group.
        /// </summary>
        internal static string RadGrid_GroupingSettings_ExpandTooltip {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; .
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupByFieldsSeparator {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupByFieldsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... group continued from the previous page..
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupContinuedFormatString {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupContinuedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group continues on the next page..
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupContinuesFormatString {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupContinuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} of {1} items..
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupSplitDisplayFormat {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupSplitDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}).
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupSplitFormat {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupSplitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to cancel grouping.
        /// </summary>
        internal static string RadGrid_GroupingSettings_UnGroupButtonTooltip {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_UnGroupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag out of the bar to ungroup.
        /// </summary>
        internal static string RadGrid_GroupingSettings_UnGroupTooltip {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_UnGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header and drop it here to group by that column.
        /// </summary>
        internal static string RadGrid_GroupPanel_Text {
            get {
                return ResourceManager.GetString("RadGrid_GroupPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the column here to group.
        /// </summary>
        internal static string RadGrid_GroupPanel_ToolTip {
            get {
                return ResourceManager.GetString("RadGrid_GroupPanel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string RadGrid_HierarchySettings_CollapseTooltip {
            get {
                return ResourceManager.GetString("RadGrid_HierarchySettings_CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string RadGrid_HierarchySettings_ExpandTooltip {
            get {
                return ResourceManager.GetString("RadGrid_HierarchySettings_ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self reference collapse.
        /// </summary>
        internal static string RadGrid_HierarchySettings_SelfCollapseTooltip {
            get {
                return ResourceManager.GetString("RadGrid_HierarchySettings_SelfCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self reference expand.
        /// </summary>
        internal static string RadGrid_HierarchySettings_SelfExpandTooltip {
            get {
                return ResourceManager.GetString("RadGrid_HierarchySettings_SelfExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master table.
        /// </summary>
        internal static string RadGrid_MasterTableView_Caption {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new record.
        /// </summary>
        internal static string RadGrid_MasterTableView_CommandItemSettings_AddNewRecordText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_CommandItemSettings_AddNewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RadGrid_MasterTableView_CommandItemSettings_RefreshText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_CommandItemSettings_RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RadGrid_MasterTableView_EditFormSettings_EditColumn_CancelText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_EditFormSettings_EditColumn_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string RadGrid_MasterTableView_EditFormSettings_EditColumn_EditText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_EditFormSettings_EditColumn_EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string RadGrid_MasterTableView_EditFormSettings_EditColumn_InsertText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_EditFormSettings_EditColumn_InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string RadGrid_MasterTableView_EditFormSettings_EditColumn_UpdateText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_EditFormSettings_EditColumn_UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No child records to display..
        /// </summary>
        internal static string RadGrid_MasterTableView_NoDetailRecordsText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_NoDetailRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to display..
        /// </summary>
        internal static string RadGrid_MasterTableView_NoMasterRecordsText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_NoMasterRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        internal static string RadGrid_PagerStyle_FirstPageToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        internal static string RadGrid_PagerStyle_LastPageToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Pages.
        /// </summary>
        internal static string RadGrid_PagerStyle_NextPagesToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_NextPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Pages.
        /// </summary>
        internal static string RadGrid_PagerStyle_NextPageToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {4} &amp;nbsp;Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt;, items &lt;strong&gt;{2}&lt;/strong&gt; to &lt;strong&gt;{3}&lt;/strong&gt; of &lt;strong&gt;{5}&lt;/strong&gt;..
        /// </summary>
        internal static string RadGrid_PagerStyle_PagerTextFormat {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_PagerTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size :.
        /// </summary>
        internal static string RadGrid_PagerStyle_PageSizeLabelText {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_PageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Pages.
        /// </summary>
        internal static string RadGrid_PagerStyle_PrevPagesToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_PrevPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        internal static string RadGrid_PagerStyle_PrevPageToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted asc.
        /// </summary>
        internal static string RadGrid_SortingSettings_SortedAscToolTip {
            get {
                return ResourceManager.GetString("RadGrid_SortingSettings_SortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted desc.
        /// </summary>
        internal static string RadGrid_SortingSettings_SortedDescToolTip {
            get {
                return ResourceManager.GetString("RadGrid_SortingSettings_SortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to sort.
        /// </summary>
        internal static string RadGrid_SortingSettings_SortToolTip {
            get {
                return ResourceManager.GetString("RadGrid_SortingSettings_SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string RadGrid_StatusBarSettings_LoadingText {
            get {
                return ResourceManager.GetString("RadGrid_StatusBarSettings_LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string RadGrid_StatusBarSettings_ReadyText {
            get {
                return ResourceManager.GetString("RadGrid_StatusBarSettings_ReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadGrid.
        /// </summary>
        internal static string RadGrid_ToolTip {
            get {
                return ResourceManager.GetString("RadGrid_ToolTip", resourceCulture);
            }
        }
    }
}
