//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RadGrid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadGrid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Resources.RadGrid", typeof(RadGrid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        internal static string EditColumnText {
            get {
                return ResourceManager.GetString("EditColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potáhnete pro seskupeni anebo změnu pořadí.
        /// </summary>
        internal static string RadGrid_ClientSettings_ClientMessages_DragToGroupOrReorder {
            get {
                return ResourceManager.GetString("RadGrid_ClientSettings_ClientMessages_DragToGroupOrReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potáhnete pro změnu velikosti.
        /// </summary>
        internal static string RadGrid_ClientSettings_ClientMessages_DragToResize {
            get {
                return ResourceManager.GetString("RadGrid_ClientSettings_ClientMessages_DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesunte sem pro změnu pořadí.
        /// </summary>
        internal static string RadGrid_ClientSettings_ClientMessages_DropHereToReorder {
            get {
                return ResourceManager.GetString("RadGrid_ClientSettings_ClientMessages_DropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stránka {0} z {1}.
        /// </summary>
        internal static string RadGrid_ClientSettings_ClientMessages_PagerTooltipFormatString {
            get {
                return ResourceManager.GetString("RadGrid_ClientSettings_ClientMessages_PagerTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr.
        /// </summary>
        internal static string RadGrid_FilterMenu_ToolTip {
            get {
                return ResourceManager.GetString("RadGrid_FilterMenu_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbalit skupinu.
        /// </summary>
        internal static string RadGrid_GroupingSettings_CollapseTooltip {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozbalit skupinu.
        /// </summary>
        internal static string RadGrid_GroupingSettings_ExpandTooltip {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; .
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupByFieldsSeparator {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupByFieldsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... seskupení pokračující z předcházející stránky..
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupContinuedFormatString {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupContinuedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seskupení pokračuje na další stránce..
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupContinuesFormatString {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupContinuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazených {0} z {1} záznamů..
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupSplitDisplayFormat {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupSplitDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}).
        /// </summary>
        internal static string RadGrid_GroupingSettings_GroupSplitFormat {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_GroupSplitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknete zde pro zrušení seskupení.
        /// </summary>
        internal static string RadGrid_GroupingSettings_UnGroupButtonTooltip {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_UnGroupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přemístete tento sloupec mimo panel, jestli chcete zrušit seskupování podle nej.
        /// </summary>
        internal static string RadGrid_GroupingSettings_UnGroupTooltip {
            get {
                return ResourceManager.GetString("RadGrid_GroupingSettings_UnGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem přesunte sloupec, podle ktorého chcete seskupovat.
        /// </summary>
        internal static string RadGrid_GroupPanel_Text {
            get {
                return ResourceManager.GetString("RadGrid_GroupPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem přesunte sloupec, podle ktorého chcete seskupovat.
        /// </summary>
        internal static string RadGrid_GroupPanel_ToolTip {
            get {
                return ResourceManager.GetString("RadGrid_GroupPanel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbalit.
        /// </summary>
        internal static string RadGrid_HierarchySettings_CollapseTooltip {
            get {
                return ResourceManager.GetString("RadGrid_HierarchySettings_CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozbalit.
        /// </summary>
        internal static string RadGrid_HierarchySettings_ExpandTooltip {
            get {
                return ResourceManager.GetString("RadGrid_HierarchySettings_ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self reference collapse.
        /// </summary>
        internal static string RadGrid_HierarchySettings_SelfCollapseTooltip {
            get {
                return ResourceManager.GetString("RadGrid_HierarchySettings_SelfCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self reference expand.
        /// </summary>
        internal static string RadGrid_HierarchySettings_SelfExpandTooltip {
            get {
                return ResourceManager.GetString("RadGrid_HierarchySettings_SelfExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master tabuľka.
        /// </summary>
        internal static string RadGrid_MasterTableView_Caption {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat nový záznam.
        /// </summary>
        internal static string RadGrid_MasterTableView_CommandItemSettings_AddNewRecordText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_CommandItemSettings_AddNewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnovit.
        /// </summary>
        internal static string RadGrid_MasterTableView_CommandItemSettings_RefreshText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_CommandItemSettings_RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        internal static string RadGrid_MasterTableView_EditFormSettings_EditColumn_CancelText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_EditFormSettings_EditColumn_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        internal static string RadGrid_MasterTableView_EditFormSettings_EditColumn_EditText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_EditFormSettings_EditColumn_EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        internal static string RadGrid_MasterTableView_EditFormSettings_EditColumn_InsertText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_EditFormSettings_EditColumn_InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava.
        /// </summary>
        internal static string RadGrid_MasterTableView_EditFormSettings_EditColumn_UpdateText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_EditFormSettings_EditColumn_UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádna data..
        /// </summary>
        internal static string RadGrid_MasterTableView_NoDetailRecordsText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_NoDetailRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádna data..
        /// </summary>
        internal static string RadGrid_MasterTableView_NoMasterRecordsText {
            get {
                return ResourceManager.GetString("RadGrid_MasterTableView_NoMasterRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to První stránka.
        /// </summary>
        internal static string RadGrid_PagerStyle_FirstPageToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední stránka.
        /// </summary>
        internal static string RadGrid_PagerStyle_LastPageToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ďaľší stránky.
        /// </summary>
        internal static string RadGrid_PagerStyle_NextPagesToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_NextPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ďaľší stránka.
        /// </summary>
        internal static string RadGrid_PagerStyle_NextPageToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4} &lt;strong&gt;{5}&lt;/strong&gt; záznamů v &lt;strong&gt;{1}&lt;/strong&gt; stránkach.
        /// </summary>
        internal static string RadGrid_PagerStyle_PagerTextFormat {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_PagerTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet záznamů na stránku :.
        /// </summary>
        internal static string RadGrid_PagerStyle_PageSizeLabelText {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_PageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předešlé stránky.
        /// </summary>
        internal static string RadGrid_PagerStyle_PrevPagesToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_PrevPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předešlá stránka.
        /// </summary>
        internal static string RadGrid_PagerStyle_PrevPageToolTip {
            get {
                return ResourceManager.GetString("RadGrid_PagerStyle_PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Třídit sestupne.
        /// </summary>
        internal static string RadGrid_SortingSettings_SortedAscToolTip {
            get {
                return ResourceManager.GetString("RadGrid_SortingSettings_SortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Třídit vzestupne.
        /// </summary>
        internal static string RadGrid_SortingSettings_SortedDescToolTip {
            get {
                return ResourceManager.GetString("RadGrid_SortingSettings_SortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknete zde pro setřídení.
        /// </summary>
        internal static string RadGrid_SortingSettings_SortToolTip {
            get {
                return ResourceManager.GetString("RadGrid_SortingSettings_SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načítavam....
        /// </summary>
        internal static string RadGrid_StatusBarSettings_LoadingText {
            get {
                return ResourceManager.GetString("RadGrid_StatusBarSettings_LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připraven.
        /// </summary>
        internal static string RadGrid_StatusBarSettings_ReadyText {
            get {
                return ResourceManager.GetString("RadGrid_StatusBarSettings_ReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadGrid.
        /// </summary>
        internal static string RadGrid_ToolTip {
            get {
                return ResourceManager.GetString("RadGrid_ToolTip", resourceCulture);
            }
        }
    }
}
