//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHP.Resources.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město :.
        /// </summary>
        public static string AddressControl_City {
            get {
                return ResourceManager.GetString("AddressControl_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email :.
        /// </summary>
        public static string AddressControl_Email {
            get {
                return ResourceManager.GetString("AddressControl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno :.
        /// </summary>
        public static string AddressControl_FirstName {
            get {
                return ResourceManager.GetString("AddressControl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČO :.
        /// </summary>
        public static string AddressControl_Id1 {
            get {
                return ResourceManager.GetString("AddressControl_Id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIČ :.
        /// </summary>
        public static string AddressControl_Id2 {
            get {
                return ResourceManager.GetString("AddressControl_Id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČ DPH :.
        /// </summary>
        public static string AddressControl_Id3 {
            get {
                return ResourceManager.GetString("AddressControl_Id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení :.
        /// </summary>
        public static string AddressControl_LastName {
            get {
                return ResourceManager.GetString("AddressControl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka :.
        /// </summary>
        public static string AddressControl_Notes {
            get {
                return ResourceManager.GetString("AddressControl_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma :.
        /// </summary>
        public static string AddressControl_Organization {
            get {
                return ResourceManager.GetString("AddressControl_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon :.
        /// </summary>
        public static string AddressControl_Phone {
            get {
                return ResourceManager.GetString("AddressControl_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stát :.
        /// </summary>
        public static string AddressControl_State {
            get {
                return ResourceManager.GetString("AddressControl_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice :.
        /// </summary>
        public static string AddressControl_Street {
            get {
                return ResourceManager.GetString("AddressControl_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ :.
        /// </summary>
        public static string AddressControl_Zip {
            get {
                return ResourceManager.GetString("AddressControl_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přednastavená hodnota :.
        /// </summary>
        public static string AdminAttributeControl_DefaultValue {
            get {
                return ResourceManager.GetString("AdminAttributeControl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název :.
        /// </summary>
        public static string AdminAttributeControl_Name {
            get {
                return ResourceManager.GetString("AdminAttributeControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ :.
        /// </summary>
        public static string AdminAttributeControl_Type {
            get {
                return ResourceManager.GetString("AdminAttributeControl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přednastavená hodnota.
        /// </summary>
        public static string AdminAttributesControl_ColumnDefaultValue {
            get {
                return ResourceManager.GetString("AdminAttributesControl_ColumnDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string AdminAttributesControl_ColumnName {
            get {
                return ResourceManager.GetString("AdminAttributesControl_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string AdminAttributesControl_ColumnType {
            get {
                return ResourceManager.GetString("AdminAttributesControl_ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový atribut.
        /// </summary>
        public static string AdminAttributesControl_NewAttributeButton_Text {
            get {
                return ResourceManager.GetString("AdminAttributesControl_NewAttributeButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        public static string AdminAttributeTypeControl_AddValueButtonText {
            get {
                return ResourceManager.GetString("AdminAttributeTypeControl_AddValueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string AdminAttributeTypeControl_FromLabel {
            get {
                return ResourceManager.GetString("AdminAttributeTypeControl_FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat vybrané.
        /// </summary>
        public static string AdminAttributeTypeControl_RemoveSelectedValueButtonText {
            get {
                return ResourceManager.GetString("AdminAttributeTypeControl_RemoveSelectedValueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string AdminAttributeTypeControl_ToLabel {
            get {
                return ResourceManager.GetString("AdminAttributeTypeControl_ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string AdminAttributeTypeControl_ValueLabelText {
            get {
                return ResourceManager.GetString("AdminAttributeTypeControl_ValueLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributy kategorie.
        /// </summary>
        public static string AdminCategoriesControl_AttributesToolTip {
            get {
                return ResourceManager.GetString("AdminCategoriesControl_AttributesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Alias.
        /// </summary>
        public static string AdminCategoriesControl_ColumnAlias {
            get {
                return ResourceManager.GetString("AdminCategoriesControl_ColumnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string AdminCategoriesControl_ColumnName {
            get {
                return ResourceManager.GetString("AdminCategoriesControl_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pořadí.
        /// </summary>
        public static string AdminCategoriesControl_ColumnOrder {
            get {
                return ResourceManager.GetString("AdminCategoriesControl_ColumnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová kategorie.
        /// </summary>
        public static string AdminCategoriesControl_NewCategoryButton_Text {
            get {
                return ResourceManager.GetString("AdminCategoriesControl_NewCategoryButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podkategorie.
        /// </summary>
        public static string AdminCategoriesControl_SubCategoriesToolTip {
            get {
                return ResourceManager.GetString("AdminCategoriesControl_SubCategoriesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název :.
        /// </summary>
        public static string AdminCategoryControl_Name {
            get {
                return ResourceManager.GetString("AdminCategoryControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pořadí :.
        /// </summary>
        public static string AdminCategoryControl_Order {
            get {
                return ResourceManager.GetString("AdminCategoryControl_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url alias :.
        /// </summary>
        public static string AdminCategoryControl_UrlAlias {
            get {
                return ResourceManager.GetString("AdminCategoryControl_UrlAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum objednávky.
        /// </summary>
        public static string AdminOrdersControl_ColumnOrderDate {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo.
        /// </summary>
        public static string AdminOrdersControl_ColumnOrderNumber {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        public static string AdminOrdersControl_ColumnOrderStatus {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaplaceno.
        /// </summary>
        public static string AdminOrdersControl_ColumnPayed {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úhrada.
        /// </summary>
        public static string AdminOrdersControl_ColumnPayment {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem.
        /// </summary>
        public static string AdminOrdersControl_ColumnPriceTotal {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnPriceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem s DPH.
        /// </summary>
        public static string AdminOrdersControl_ColumnPriceTotalWVAT {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnPriceTotalWVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přeprava.
        /// </summary>
        public static string AdminOrdersControl_ColumnShipment {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        public static string AdminOrdersControl_ColumnUser {
            get {
                return ResourceManager.GetString("AdminOrdersControl_ColumnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat.
        /// </summary>
        public static string AdminOrdersControl_Find {
            get {
                return ResourceManager.GetString("AdminOrdersControl_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - všechny -.
        /// </summary>
        public static string AdminOrdersControl_OptionAll {
            get {
                return ResourceManager.GetString("AdminOrdersControl_OptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo objednávky :.
        /// </summary>
        public static string AdminOrdersControl_OrderNumber {
            get {
                return ResourceManager.GetString("AdminOrdersControl_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav :.
        /// </summary>
        public static string AdminOrdersControl_OrderStatus {
            get {
                return ResourceManager.GetString("AdminOrdersControl_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přeprava :.
        /// </summary>
        public static string AdminOrdersControl_Shipment {
            get {
                return ResourceManager.GetString("AdminOrdersControl_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vložit produkt do košíku.
        /// </summary>
        public static string AdminProductControl_AddProductToCart_ToolTip {
            get {
                return ResourceManager.GetString("AdminProductControl_AddProductToCart_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doplnkové vlastnosti.
        /// </summary>
        public static string AdminProductControl_AdvancedProperties {
            get {
                return ResourceManager.GetString("AdminProductControl_AdvancedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativní produkty.
        /// </summary>
        public static string AdminProductControl_AlternateProducts {
            get {
                return ResourceManager.GetString("AdminProductControl_AlternateProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupnost :.
        /// </summary>
        public static string AdminProductControl_Availability {
            get {
                return ResourceManager.GetString("AdminProductControl_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní vlastnosti.
        /// </summary>
        public static string AdminProductControl_BasicProperties {
            get {
                return ResourceManager.GetString("AdminProductControl_BasicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie :.
        /// </summary>
        public static string AdminProductControl_Categories {
            get {
                return ResourceManager.GetString("AdminProductControl_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód produktu :.
        /// </summary>
        public static string AdminProductControl_Code {
            get {
                return ResourceManager.GetString("AdminProductControl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis :.
        /// </summary>
        public static string AdminProductControl_Description {
            get {
                return ResourceManager.GetString("AdminProductControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleva :.
        /// </summary>
        public static string AdminProductControl_Discount {
            get {
                return ResourceManager.GetString("AdminProductControl_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ slevy :.
        /// </summary>
        public static string AdminProductControl_DiscountType {
            get {
                return ResourceManager.GetString("AdminProductControl_DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string AdminProductControl_DiscountType_Percent {
            get {
                return ResourceManager.GetString("AdminProductControl_DiscountType_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma.
        /// </summary>
        public static string AdminProductControl_DiscountType_Price {
            get {
                return ResourceManager.GetString("AdminProductControl_DiscountType_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvýraznení produktu :.
        /// </summary>
        public static string AdminProductControl_Highlights {
            get {
                return ResourceManager.GetString("AdminProductControl_Highlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výrobce :.
        /// </summary>
        public static string AdminProductControl_Manufacturer {
            get {
                return ResourceManager.GetString("AdminProductControl_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název :.
        /// </summary>
        public static string AdminProductControl_Name {
            get {
                return ResourceManager.GetString("AdminProductControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotografie.
        /// </summary>
        public static string AdminProductControl_Photos {
            get {
                return ResourceManager.GetString("AdminProductControl_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena bez DPH :.
        /// </summary>
        public static string AdminProductControl_Price {
            get {
                return ResourceManager.GetString("AdminProductControl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena s DPH :.
        /// </summary>
        public static string AdminProductControl_PriceWVAT {
            get {
                return ResourceManager.GetString("AdminProductControl_PriceWVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, byl přidán do nákupního košíku v počtu {1}Ks..
        /// </summary>
        public static string AdminProductControl_ProductWasAddedToCart_Message {
            get {
                return ResourceManager.GetString("AdminProductControl_ProductWasAddedToCart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet kusů :.
        /// </summary>
        public static string AdminProductControl_Quantity {
            get {
                return ResourceManager.GetString("AdminProductControl_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Související produkty.
        /// </summary>
        public static string AdminProductControl_RelatedProducts {
            get {
                return ResourceManager.GetString("AdminProductControl_RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenze.
        /// </summary>
        public static string AdminProductControl_Reviews {
            get {
                return ResourceManager.GetString("AdminProductControl_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krátký popis :.
        /// </summary>
        public static string AdminProductControl_ShortDescription {
            get {
                return ResourceManager.GetString("AdminProductControl_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na sklade  :.
        /// </summary>
        public static string AdminProductControl_StorageCount {
            get {
                return ResourceManager.GetString("AdminProductControl_StorageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url alias :.
        /// </summary>
        public static string AdminProductControl_UrlAlias {
            get {
                return ResourceManager.GetString("AdminProductControl_UrlAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPH :.
        /// </summary>
        public static string AdminProductControl_VAT {
            get {
                return ResourceManager.GetString("AdminProductControl_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie :.
        /// </summary>
        public static string AdminProductRelationControl_Category {
            get {
                return ResourceManager.GetString("AdminProductRelationControl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie článku :.
        /// </summary>
        public static string AdminProductReviewsControl_Category {
            get {
                return ResourceManager.GetString("AdminProductReviewsControl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Alias.
        /// </summary>
        public static string AdminProductsControl_ColumnAlias {
            get {
                return ResourceManager.GetString("AdminProductsControl_ColumnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód.
        /// </summary>
        public static string AdminProductsControl_ColumnCode {
            get {
                return ResourceManager.GetString("AdminProductsControl_ColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string AdminProductsControl_ColumnDescription {
            get {
                return ResourceManager.GetString("AdminProductsControl_ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleva.
        /// </summary>
        public static string AdminProductsControl_ColumnDiscount {
            get {
                return ResourceManager.GetString("AdminProductsControl_ColumnDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ slevy.
        /// </summary>
        public static string AdminProductsControl_ColumnDiscountType {
            get {
                return ResourceManager.GetString("AdminProductsControl_ColumnDiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výrobce.
        /// </summary>
        public static string AdminProductsControl_ColumnManufacturer {
            get {
                return ResourceManager.GetString("AdminProductsControl_ColumnManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string AdminProductsControl_ColumnName {
            get {
                return ResourceManager.GetString("AdminProductsControl_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string AdminProductsControl_ColumnPrice {
            get {
                return ResourceManager.GetString("AdminProductsControl_ColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový produkt.
        /// </summary>
        public static string AdminProductsControl_NewProductButton_Text {
            get {
                return ResourceManager.GetString("AdminProductsControl_NewProductButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string AdminUrlAliasesControl_AliasType_Categories {
            get {
                return ResourceManager.GetString("AdminUrlAliasesControl_AliasType_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty.
        /// </summary>
        public static string AdminUrlAliasesControl_AliasType_Products {
            get {
                return ResourceManager.GetString("AdminUrlAliasesControl_AliasType_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zpět.
        /// </summary>
        public static string BackLink {
            get {
                return ResourceManager.GetString("BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string CancelButton_Text {
            get {
                return ResourceManager.GetString("CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo objednávky.
        /// </summary>
        public static string CartControl_ColumnId {
            get {
                return ResourceManager.GetString("CartControl_ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string CartControl_ColumnName {
            get {
                return ResourceManager.GetString("CartControl_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena/Ks.
        /// </summary>
        public static string CartControl_ColumnPrice {
            get {
                return ResourceManager.GetString("CartControl_ColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem.
        /// </summary>
        public static string CartControl_ColumnPriceTotal {
            get {
                return ResourceManager.GetString("CartControl_ColumnPriceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem s DPH.
        /// </summary>
        public static string CartControl_ColumnPriceTotalWithVAT {
            get {
                return ResourceManager.GetString("CartControl_ColumnPriceTotalWithVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena se slevou/Ks.
        /// </summary>
        public static string CartControl_ColumnPriceWithDiscount {
            get {
                return ResourceManager.GetString("CartControl_ColumnPriceWithDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ks.
        /// </summary>
        public static string CartControl_ColumnQuantity {
            get {
                return ResourceManager.GetString("CartControl_ColumnQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat.
        /// </summary>
        public static string CartControl_ContinueButton_Text {
            get {
                return ResourceManager.GetString("CartControl_ContinueButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa pro doručení.
        /// </summary>
        public static string CartControl_DeliveryAddress {
            get {
                return ResourceManager.GetString("CartControl_DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturační adresa.
        /// </summary>
        public static string CartControl_InvoiceAddress {
            get {
                return ResourceManager.GetString("CartControl_InvoiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit.
        /// </summary>
        public static string CartControl_LoginButton_Text {
            get {
                return ResourceManager.GetString("CartControl_LoginButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat.
        /// </summary>
        public static string CartControl_NextStepButton_Text {
            get {
                return ResourceManager.GetString("CartControl_NextStepButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednat.
        /// </summary>
        public static string CartControl_OrderButton_Text {
            get {
                return ResourceManager.GetString("CartControl_OrderButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spůsob platby :.
        /// </summary>
        public static string CartControl_Payment {
            get {
                return ResourceManager.GetString("CartControl_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spůsob přepravy :.
        /// </summary>
        public static string CartControl_Shipment {
            get {
                return ResourceManager.GetString("CartControl_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » zobrazit košík.
        /// </summary>
        public static string CartControl_ShowCart {
            get {
                return ResourceManager.GetString("CartControl_ShowCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona :.
        /// </summary>
        public static string ClassifierControl_Icon {
            get {
                return ResourceManager.GetString("ClassifierControl_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název :.
        /// </summary>
        public static string ClassifierControl_Name {
            get {
                return ResourceManager.GetString("ClassifierControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka :.
        /// </summary>
        public static string ClassifierControl_Notes {
            get {
                return ResourceManager.GetString("ClassifierControl_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit ikonu.
        /// </summary>
        public static string ClassifierControl_RemoveIcon {
            get {
                return ResourceManager.GetString("ClassifierControl_RemoveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat položku.
        /// </summary>
        public static string ClassifiersControl_AddItem {
            get {
                return ResourceManager.GetString("ClassifiersControl_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona.
        /// </summary>
        public static string ClassifiersControl_ColumnIcon {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string ClassifiersControl_ColumnName {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string ClassifiersControl_ColumnNotes {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procent.
        /// </summary>
        public static string ClassifiersControl_ColumnPrecent {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnPrecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string ClassifiersControl_ColumnPrice {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena s DPH.
        /// </summary>
        public static string ClassifiersControl_ColumnPriceWithVAT {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnPriceWithVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výměnný kurz.
        /// </summary>
        public static string ClassifiersControl_ColumnRate {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol měny.
        /// </summary>
        public static string ClassifiersControl_ColumnSymbol {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPH.
        /// </summary>
        public static string ClassifiersControl_ColumnVAT {
            get {
                return ResourceManager.GetString("ClassifiersControl_ColumnVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to komentare.
        /// </summary>
        public static string Comment_AliasText {
            get {
                return ResourceManager.GetString("Comment_AliasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte měnu.
        /// </summary>
        public static string CurrencyChoiceControl_ChoiceButtonText {
            get {
                return ResourceManager.GetString("CurrencyChoiceControl_ChoiceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výměnný kurz :.
        /// </summary>
        public static string CurrencyControl_Rate {
            get {
                return ResourceManager.GetString("CurrencyControl_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol měny :.
        /// </summary>
        public static string CurrencyControl_Symbol {
            get {
                return ResourceManager.GetString("CurrencyControl_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat tento záznam?.
        /// </summary>
        public static string DeleteItemQuestion {
            get {
                return ResourceManager.GetString("DeleteItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string FilterControl_CancelFindButtonText {
            get {
                return ResourceManager.GetString("FilterControl_CancelFindButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhledat.
        /// </summary>
        public static string FilterControl_FindButtonText {
            get {
                return ResourceManager.GetString("FilterControl_FindButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat položku.
        /// </summary>
        public static string GridView_ToolTip_DeleteItem {
            get {
                return ResourceManager.GetString("GridView_ToolTip_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string GridView_ToolTip_EditItem {
            get {
                return ResourceManager.GetString("GridView_ToolTip_EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa pro doručení.
        /// </summary>
        public static string OrderControl_DeliveryAddress {
            get {
                return ResourceManager.GetString("OrderControl_DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturační adresa.
        /// </summary>
        public static string OrderControl_InvoiceAddress {
            get {
                return ResourceManager.GetString("OrderControl_InvoiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednat.
        /// </summary>
        public static string OrderControl_OrderButton_Text {
            get {
                return ResourceManager.GetString("OrderControl_OrderButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka č.: {0}.
        /// </summary>
        public static string OrderControl_OrderNumberFormatText {
            get {
                return ResourceManager.GetString("OrderControl_OrderNumberFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednané zboží.
        /// </summary>
        public static string OrderControl_OrderProducts {
            get {
                return ResourceManager.GetString("OrderControl_OrderProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav obj. :.
        /// </summary>
        public static string OrderControl_OrderStatus {
            get {
                return ResourceManager.GetString("OrderControl_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrý den &lt;br/&gt;&lt;br/&gt;
        ///stav Vaší objednávky č. {0} se změnil na &lt;b&gt;{1}&lt;/b&gt;&lt;br/&gt;&lt;/br&gt;
        ///S pozdravem&lt;br/&gt;
        ///{2}.
        /// </summary>
        public static string OrderControl_OrderStatusChanged_Email_Message {
            get {
                return ResourceManager.GetString("OrderControl_OrderStatusChanged_Email_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum úhrady :.
        /// </summary>
        public static string OrderControl_PaydDate {
            get {
                return ResourceManager.GetString("OrderControl_PaydDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platba :.
        /// </summary>
        public static string OrderControl_Payment {
            get {
                return ResourceManager.GetString("OrderControl_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string OrderControl_Price {
            get {
                return ResourceManager.GetString("OrderControl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena za tovar:.
        /// </summary>
        public static string OrderControl_PriceForProducts {
            get {
                return ResourceManager.GetString("OrderControl_PriceForProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena za přepravu :.
        /// </summary>
        public static string OrderControl_PriceForShipment {
            get {
                return ResourceManager.GetString("OrderControl_PriceForShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem :.
        /// </summary>
        public static string OrderControl_PriceTotal {
            get {
                return ResourceManager.GetString("OrderControl_PriceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K úhrade s DPH :.
        /// </summary>
        public static string OrderControl_PriceTotalWVAT {
            get {
                return ResourceManager.GetString("OrderControl_PriceTotalWVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte dopravce :.
        /// </summary>
        public static string OrderControl_Shipment {
            get {
                return ResourceManager.GetString("OrderControl_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevhodný příspěvek.
        /// </summary>
        public static string ProductCommentsControl_InappropriatePost {
            get {
                return ResourceManager.GetString("ProductCommentsControl_InappropriatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reagovat.
        /// </summary>
        public static string ProductCommentsControl_Reply {
            get {
                return ResourceManager.GetString("ProductCommentsControl_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativní produkty.
        /// </summary>
        public static string ProductControl_AlternateProducts {
            get {
                return ResourceManager.GetString("ProductControl_AlternateProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupnost :.
        /// </summary>
        public static string ProductControl_Availability {
            get {
                return ResourceManager.GetString("ProductControl_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentáře.
        /// </summary>
        public static string ProductControl_CommentsCount {
            get {
                return ResourceManager.GetString("ProductControl_CommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string ProductControl_Description {
            get {
                return ResourceManager.GetString("ProductControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena bez DPH :.
        /// </summary>
        public static string ProductControl_Price {
            get {
                return ResourceManager.GetString("ProductControl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena s DPH :.
        /// </summary>
        public static string ProductControl_PriceWVAT {
            get {
                return ResourceManager.GetString("ProductControl_PriceWVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenze.
        /// </summary>
        public static string ProductControl_ProductReviews {
            get {
                return ResourceManager.GetString("ProductControl_ProductReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Související produkty.
        /// </summary>
        public static string ProductControl_RelatedProducts {
            get {
                return ResourceManager.GetString("ProductControl_RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyly nalezeny žádne produkty.
        /// </summary>
        public static string ProductsControl_NoProductsFound_Message {
            get {
                return ResourceManager.GetString("ProductsControl_NoProductsFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výraz.
        /// </summary>
        public static string ProductsFilterControl_Expression {
            get {
                return ResourceManager.GetString("ProductsFilterControl_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výrobce.
        /// </summary>
        public static string ProductsFilterControl_Manufacturer {
            get {
                return ResourceManager.GetString("ProductsFilterControl_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena od.
        /// </summary>
        public static string ProductsFilterControl_PriceFrom {
            get {
                return ResourceManager.GetString("ProductsFilterControl_PriceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        public static string ProductsFilterControl_PriceTo {
            get {
                return ResourceManager.GetString("ProductsFilterControl_PriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seřadit.
        /// </summary>
        public static string ProductsFilterControl_Sort {
            get {
                return ResourceManager.GetString("ProductsFilterControl_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názvu.
        /// </summary>
        public static string ProductsFilterControl_SortBy_NameASC_Label {
            get {
                return ResourceManager.GetString("ProductsFilterControl_SortBy_NameASC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductsFilterControl_SortBy_None_Label {
            get {
                return ResourceManager.GetString("ProductsFilterControl_SortBy_None_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od nejlevnejšího.
        /// </summary>
        public static string ProductsFilterControl_SortBy_PriceASC_Label {
            get {
                return ResourceManager.GetString("ProductsFilterControl_SortBy_PriceASC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od nejdražšího.
        /// </summary>
        public static string ProductsFilterControl_SortBy_PriceDESC_Label {
            get {
                return ResourceManager.GetString("ProductsFilterControl_SortBy_PriceDESC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string SaveButton_Text {
            get {
                return ResourceManager.GetString("SaveButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena :.
        /// </summary>
        public static string ShipmentControl_Price {
            get {
                return ResourceManager.GetString("ShipmentControl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPH :.
        /// </summary>
        public static string ShipmentControl_VAT {
            get {
                return ResourceManager.GetString("ShipmentControl_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procent :.
        /// </summary>
        public static string VATControl_Percent {
            get {
                return ResourceManager.GetString("VATControl_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s DPH.
        /// </summary>
        public static string WithVAT {
            get {
                return ResourceManager.GetString("WithVAT", resourceCulture);
            }
        }
    }
}
